### ISSUE TITLE
Async compilation

### ISSUE THREAD

**Issue by GianlucaGuarini** [ariporad/pirates#53]
Hi thanks for this great script, I am using it for the new riotjs ssr module. I have a question: is it possible to compile the required files asynchronously?

```js
import {addHook} from 'pirates'

addHook(
  async function(source, filename) {
     return await compile(source)
  },
  { exts: ['.riot'] }
)
```

**Comment by sjockers** [comment]
I would be very interested in this as well. I'd like to use this to build tooling for Svelte, which has an asynchronous preprocessing method.

**Comment by GianlucaGuarini** [comment]
The new riot compiler was enough flexible to handle also [sync compiling](https://github.com/riot/ssr). I guess async compilation is not a good idea anyways.

**Comment by sjockers** [comment]
The actual compilation in Svelte is also synchronous. What's async is the preprocessing part, where you can hook preprocessors in, such as LESS, SASS, etc. – which may in turn rely on async compilation. In order to generically handle compilation and preprocessing in a hook, you'd need some way to do it async.

**Comment by GianlucaGuarini** [comment]
I am closing this issue since the node API commonjs API is completely synchronous. There is no simple solution to hook async loading without blocking the node process main thread. Many thanks for this great script!
